# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvc < Formula
  desc "tfvc is a tool for checking terraform provider and module versions are up to date"
  homepage "https://github.com/tfverch/tfvc"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tfverch/tfvc/releases/download/v0.4.0/tfvc_0.4.0_Darwin_arm64.tar.gz"
      sha256 "1ea9168ca2a85d1ca7db460f1e597d34adbbf80804208dfa6b9074c2d8bb6e8b"

      def install
        bin.install "tfvc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tfverch/tfvc/releases/download/v0.4.0/tfvc_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "257d1cacbc926565673d8d6b955bf60ad84ed21ee284d6a091ea205fd42d0d47"

      def install
        bin.install "tfvc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tfverch/tfvc/releases/download/v0.4.0/tfvc_0.4.0_Linux_x86_64.tar.gz"
      sha256 "c2ee5759f37e5419771a949bf952cd342bd9835603d6f130253a449560e477e9"

      def install
        bin.install "tfvc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfverch/tfvc/releases/download/v0.4.0/tfvc_0.4.0_Linux_arm64.tar.gz"
      sha256 "a495c508a68dc61642f13755a67c64f4493925302de4e513977b09137b48e51c"

      def install
        bin.install "tfvc"
      end
    end
  end
end
